package Locations

enum class LocationNames {
    COURTYARD, KITCHEN, DINING_HALL, MAIN_CORRIDOR, LIBRARY, ARMORY, WITCHERS_LABORATORY, UPPER_COURYARD,

    INN, CRYPT, OLD_MILL, CHURCH, REVEREND_HOUSE, ABIGAIL_HOUSE,

    CEMETERY, DUNGEON, DETECTIVE_HOUSE, VIZIMA_SEWERS, THE_HAIRY_BEAR,

    MARKETPLACE, TOWN_HALL, VIVALDI_BANK,

    DEAD
}